kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    giantswarm.io/service-type: "managed"
spec:
  podSelector:
    matchLabels:
      k8s-app: {{ .Values.name }}
  ingress:
  - ports:
    - port: {{ .Values.port }}
      protocol: TCP
    from:
    - podSelector:
        matchLabels:
          app: net-exporter
    - podSelector:
        matchLabels:
          app: prometheus
    {{ range $index, $workerSubnet := .Values.configmap.workerSubnets }}
    - ipBlock:
        cidr: {{ $workerSubnet }}
    {{ end }}
  egress:
  - ports:
    - port: {{ .Values.port }}
      protocol: TCP
    to:
    - podSelector:
        matchLabels:
          app: {{ .Values.name }}
  - ports:
    - port: {{ .Values.dns.port }}
      protocol: UDP
    - port: {{ .Values.dns.port }}
      protocol: TCP
    to:
    - podSelector:
        matchLabels:
          k8s-app: {{ .Values.dns.label }}
  - ports:
    - port: 443
      protocol: TCP
    to:
    {{ $privateSubnets := list "10.0.0.0/8" "172.16.0.0/12" "192.168.0.0/16" }}
    {{ range $index, $privateSubnet := $privateSubnets }}
    - ipBlock:
        cidr: {{ $privateSubnet }}
    {{ end }}
  policyTypes:
  - Ingress
  - Egress
